The fuzzer build is failing (correctly) because of issues with bn::G1::from_compressed
error[E0599]: no function or associated item named  found for type  in the current scope
  --> /home/runner/work/zebra/zebra/zebra-crypto/src/pghr13.rs:82:20
   |
82 |             h: G1::from_compressed(&data[263..296])?,
   |                    ^^^^^^^^^^^^^^^ function or associated item not found in

error: aborting due to 9 previous errors